version: "3.7"
services:
  
  mongo:
    image: mongo
    container_name: mongo_database
    restart: always
    ports:
      - 27018:27017
    volumes:
      - .monogdbdata:/data/db


volumes:
  mongodbdata: