version: "3.7"
services:
  
  mongo:
    image: mongo
    container_name: mongo_database
    restart: always
    ports:
      - 27018:27017
    volumes:
      - .monogdbdata:/data/db
  
  postgre:
    image: postgres
    container_name: postgres_database
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Ecommerce.UserManagementDB
    volumes:
      - .postgresdata:/var/lib/postgresql/data
    


volumes:
  mongodbdata:
  postgresdata: