version: "3.7"
services:
  
  mongo:
    image: mongo
    container_name: mongo_database
    restart: always
    ports:
      - 27018:27017
    volumes:
      - .monogdbdata:/data/db
  
  postgre:
    image: postgres
    container_name: postgres_database
    restart: always
    ports:
      - 5433:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: Ecommerce.UserManagementDB
    volumes:
      - .postgresdata:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    ports:
      - 5673:5672
      - 15673:15672
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest
    volumes:
      - .rabbitmqdata:/var/lib/rabbitmq
    hostname: rabbitmq


volumes:
  .mongodbdata:
  .postgresdata:
  .rabbitmqdata: